### ISSUE TITLE
Risque de conflitc pour les utilisateurs

### ISSUE THREAD

**Issue by RignonNoel** [MaisonLogicielLibre/codetributhon#111]
Dans le README il est marqué:

```
Faire votre propre migration avec les commandes python manage.py makemigrations events projects faq et python migrate
```

Si le client fait un makemigrations de son instance, il risque de ce retrouver avec un conflit à la prochaine mise à jour de codetributhon. Les migrations sont censé être faite en même temps que le code.

**Comment by willkoua** [comment]
ok. Je vais le modifier. Je l'avais mis a cause d'un probleme que j'avais eu mais maintenant, tout fonctionne
