### ISSUE TITLE
revoir le design de la page des événements 

### ISSUE THREAD

**Issue by willkoua** [MaisonLogicielLibre/codetributhon#42]
revoir le design de la version mobile et celui de la version normale

**Comment by MaDumont** [comment]
Je ne suis pas certain de comprendre ce qu'il y a de pas correct. @willkoua pourrais tu mettre des captures d'ecran de ce qui faut changer.

**Comment by willkoua** [comment]
En faite, aucun design n'a été défini pour faute de temps. Donc, il faudrait voir ce qu'on peut faire de plus beau que ce qu'il y a actuellement

**Comment by MaDumont** [comment]
Mais je comprend pas ce que tu veux dire par "lorsque la page est a ça moitie", est-ce que tu parles de la largeur (genre sur mobile) ou est-ce que tu parles lorsqu'on a descendu dans la page?

**Comment by willkoua** [comment]
je veux parler du format mobile
