### ISSUE TITLE
arranger les boutons de partage dans la page de detail des events 

### ISSUE THREAD

**Issue by willkoua** [MaisonLogicielLibre/codetributhon#44]
les boutons sont mal positionnees

**Comment by MaDumont** [comment]
@willkoua je ne suis pas certain de ce que tu veux dire pas mal positionnees. Pourrais tu mettre une image?

**Comment by willkoua** [comment]
dans la page de visualisation des événements, il doit y avoir des boutons pour partager sur facebook, twitter et linkedin . Il faut qu'ils soient tous de la même grandeur.

**Comment by MaDumont** [comment]
Pourrais tu mettre une image, car sur mon ordi les boutons sont de la meme grandeur, mais il manque linkedin.
