### ISSUE TITLE
correction of the warning error

### ISSUE THREAD

**Issue by MaDumont** [MaisonLogicielLibre/codetributhon#97]
When starting the project, there is simple error that we can correct.

**Comment by willkoua** [comment]
soit plus explicite sur l'erreur

**Comment by MaDumont** [comment]
.../codetributhon/pages/urls.py:15: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.contrib.auth.views.login). Pass the callable instead.
  name='login'

.../codetributhon/pages/urls.py:45: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='settlement'

.../codetributhon/members/urls.py:5: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  '',

.../codetributhon/projects/urls.py:23: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='contribution_create'

.../codetributhon/events/urls.py:14: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='event_detail'
